[package]
name = "level"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
default = []
debug = ["colored"]

[dependencies]
bevy = "0.10.1"
colored = { version = "2.0.0", optional = true }
